apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomization/inflated.yaml

patches:
  - path: kustomization/patch-db-label.yaml
    target:
      kind: Deployment
      labelSelector: "component=jobservice"
  - path: kustomization/patch-db-label.yaml
    target:
      kind: Deployment
      labelSelector: "component=core"
  - path: kustomization/patch-core-config.yaml
    target:
      kind: Deployment
      labelSelector: "component=core"