harbor:
  expose:
    tls:
      certSource: secret
      secret:
        secretName: harbor-cert
    ingress:
      hosts:
        core: harbor.yogstation.net
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        #nginx.ingress.kubernetes.io/auth-tls-verify-client: "off"
        #nginx.ingress.kubernetes.io/auth-tls-secret: harbor/cloudflare-dummy-cert

  externalURL: https://harbor.yogstation.net

  persistence:
    persistentVolumeClaim:
      chartmuseum:
        storageClass: local-path
      jobservice:
        storageClass: local-path
      redis:
        storageClass: local-path
      registry:
        storageClass: local-path
      trivy:
        storageClass: local-path

  notary:
    enabled: false

  database:
    type: external
    external:
      host: "postgres.postgres"

storage:
  location: /var/lib/yogstation/harbor

email:
  host: mail.yogstation.net
  port: 465
  ssl: true
  from: harbor@yogstation.net
  user: harbor@yogstation.net
  password: