apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  template:
    spec:
      containers:
        - name: core
          env:
            - name: CONFIG_OVERWRITE_JSON
              valueFrom:
                secretKeyRef:
                  key: CONFIG_OVERWRITE_JSON
                  name: harbor-jsonconfig