apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-redis
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  hostPath:
    path: {{ (printf "%s/redis" .Values.storage.location) | quote }}
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem