apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc-trivy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: harbor-pv-trivy
  storageClassName: ""