apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc-redis
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: harbor-pv-redis
  storageClassName: ""