apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: harbor-pv
  storageClassName: ""