apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: harbor-pv-registry
  storageClassName: ""