apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  hostPath:
    path: {{ .Values.storage.location | quote }}
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem