apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-pvc-redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: harbor-pv-redis
  storageClassName: ""